services:
  sismanager:
    build: .
    container_name: sismanager
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: poetry run python run.py
